<?php $domain = get_option($this->option_namespace . '_domain');
$tel = get_option($this->option_namespace . '_tel');
$email = get_option($this->option_namespace . '_email');
$web = get_option($this->option_namespace . '_web');
$directions = get_option($this->option_namespace . '_instructions');

$image_id = get_option($this->option_namespace . '_image');
$image_url = '';
if(isset($image_id)){
    $image_url = wp_get_attachment_url($image_id);
}; ?><fieldset><div class="input-field"><label><?php _e("Image", "boilerplate"); ?>:</label><div class="image-preview"><div class="image-preview__placeholder" style="background-image: url('<?php echo $image_url; ?>')"></div><a class="image-preview-button image-preview-button--clear" href="#"><span class="image-preview-button__icon dashicons dashicons-trash"></span></a><a class="image-preview-button image-preview-button--upload" href="#"><span class="image-preview-button__icon dashicons dashicons-plus"></span></a><input class="image-preview__input" type="text" hidden name="<?php echo $this->option_namespace . '_image'; ?>" id="<?php echo $this->option_namespace . '_image'; ?>" value="<?php echo $image_id; ?>"></div></div><div class="input-field"><label><?php _e("Domain", "boilerplate"); ?>:</label><input type="text" name="<?php echo $this->option_namespace . '_domain'; ?>" id="<?php echo $this->option_namespace . '_domain'; ?>" value="<?php echo $domain; ?>"></div><div class="input-field"><label><?php _e("Telephone Number", "boilerplate"); ?>:</label><input type="tel" name="<?php echo $this->option_namespace . '_tel'; ?>" id="<?php echo $this->option_namespace . '_tel'; ?>" value="<?php echo $tel; ?>"></div><div class="input-field"><label><?php _e("Email", "boilerplate"); ?>:</label><input type="email" name="<?php echo $this->option_namespace . '_email'; ?>" id="<?php echo $this->option_namespace . '_email'; ?>" value="<?php echo $email; ?>"></div><div class="input-field"><label><?php _e("Website URL", "boilerplate"); ?>:</label><input type="url" name="<?php echo $this->option_namespace . '_web'; ?>" id="<?php echo $this->option_namespace . '_web'; ?>" value="<?php echo $web; ?>"></div><div class="input-field"><label><?php _e("Instructions", "boilerplate"); ?>:</label><textarea name="<?php echo $this->option_namespace . '_instructions'; ?>" id="<?php echo $this->option_namespace . '_instructions'; ?>"><?php echo $directions; ?></textarea></div></fieldset>